ci(build): Fix wrong variable, configs and more
- Fix wrong variable, missing variable
- Fix missing configs for kernel
- Fix wrong directory taking boot Image

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -47,7 +47,7 @@ jobs:
         echo "Kernel Version    : ${{ inputs.kernel_version }}"
         echo "Sub Level         : ${{ inputs.sub_level }}"
         echo "Patch Level       : ${{ inputs.os_patch_level }}"
-        echo "KernelSU Manager: ${{ inputs.kernel_variant }}"
+        echo "KernelSU Manager  : ${{ inputs.kernel_variant }}"
         echo "========================================"
 
     - name: Free Disk Space
@@ -300,13 +300,13 @@ jobs:
 
         if [[ "${{ inputs.android_version }}" == "android13" && "${{ inputs.kernel_version }}" == "5.15" ]]; then
           if [[ "$SUBLEVEL" -le 41 ]]; then
-            cp ${{ github.workspace }}/kernel_patches/wild/susfs_fix_patches/v${SUSFS_VERSION}/a13-5.15/namespace.c.patch ./
+            cp $KERNEL_PATCHESs/wild/susfs_fix_patches/${SUSFS_VERSION}/a13-5.15/namespace.c.patch ./
             patch -p1 < namespace.c.patch
 
-            cp ${{ github.workspace }}/kernel_patches/wild/susfs_fix_patches/v${SUSFS_VERSION}/a13-5.15/fdinfo.c.patch ./
+            cp $KERNEL_PATCHESs/wild/susfs_fix_patches/${SUSFS_VERSION}/a13-5.15/fdinfo.c.patch ./
             patch -p1 < fdinfo.c.patch
 
-            cp ${{ github.workspace }}/kernel_patches/wild/susfs_fix_patches/v${SUSFS_VERSION}/a13-5.15/open.c.patch ./
+            cp $KERNEL_PATCHESs/wild/susfs_fix_patches/${SUSFS_VERSION}/a13-5.15/open.c.patch ./
             patch -p1 < open.c.patch
 
             sed -i 's|i_uid_into_mnt(i_user_ns(&fi->inode), &fi->inode).val|fi->inode.i_uid.val|g' fs/susfs.c
@@ -468,51 +468,52 @@ jobs:
         CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
         CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
         CONFIG_KSU_SUSFS_SUS_MAP=y
+
+        # Networking Configuration
+        CONFIG_IP_NF_TARGET_TTL=y
+        CONFIG_IP6_NF_TARGET_HL=y
+        CONFIG_IP6_NF_MATCH_HL=y
+
+        # BBR TCP Congestion Control
+        CONFIG_TCP_CONG_ADVANCED=y
+        CONFIG_TCP_CONG_BBR=y
+        CONFIG_NET_SCH_FQ=y
+        # CONFIG_TCP_CONG_BIC is not set
+        # CONFIG_TCP_CONG_WESTWOOD is not set
+        # CONFIG_TCP_CONG_HTCP is not set
+
+        # IPSet Support
+        CONFIG_IP_SET=y
+        CONFIG_IP_SET_MAX=65534
+        CONFIG_IP_SET_BITMAP_IP=y
+        CONFIG_IP_SET_BITMAP_IPMAC=y
+        CONFIG_IP_SET_BITMAP_PORT=y
+        CONFIG_IP_SET_HASH_IP=y
+        CONFIG_IP_SET_HASH_IPMARK=y
+        CONFIG_IP_SET_HASH_IPPORT=y
+        CONFIG_IP_SET_HASH_IPPORTIP=y
+        CONFIG_IP_SET_HASH_IPPORTNET=y
+        CONFIG_IP_SET_HASH_IPMAC=y
+        CONFIG_IP_SET_HASH_MAC=y
+        CONFIG_IP_SET_HASH_NETPORTNET=y
+        CONFIG_IP_SET_HASH_NET=y
+        CONFIG_IP_SET_HASH_NETNET=y
+        CONFIG_IP_SET_HASH_NETPORT=y
+        CONFIG_IP_SET_HASH_NETIFACE=y
+        CONFIG_IP_SET_LIST_SET=y
         EOF
-  
+        # Apply Kernel Config for 5.10
+        if [ "${{ inputs.kernel_version }}" == "5.10" ]; then
+          sed -i 's/CONFIG_IP_SET_MAX/65534/g' "$KERNEL_ROOT/net/netfilter/ipset/ip_set_core.c"
+        fi
         # Remove check_defconfig
-        if [[ "${{ inputs.android_version }}" == "android16" && "${{ inputs.kernel_version }}" == "6.12" ]]; then
+        if [ "${{ inputs.kernel_version }}" == "6.12" ]; then
           sed -i '/name = "kernel_aarch64",/a\    check_defconfig = "disabled",' common/BUILD.bazel
           awk '/name = "kernel_aarch64"/,/^\)/ {if(/check_defconfig = "disabled"/) found=1} END{if(found) print "SUCCESS: check_defconfig = \"disabled\" is in the kernel_aarch64 block"; else print "FAILED: NOT in the kernel_aarch64 block"}' common/BUILD.bazel
         else
           sed -i 's/check_defconfig//' ./common/build.config.gki
         fi
 
-    - name: Append ashmem exports if missing
-      if: inputs.android_version == 'android16'
-      working-directory: ${{ env.KERNEL_ROOT }}
-      run: |
-        FILE=common/drivers/staging/android/ashmem.c
-        if [[ -f "$FILE" ]] && ! grep -q 'is_ashmem_file' "$FILE"; then
-        cat >>"$FILE" <<'EOF'
-        bool is_ashmem_file(struct file *file) { return false; }
-        int ashmem_area_name(struct file *file, char *name) { return 0; }
-        long ashmem_area_size(struct file *file) { return 0; }
-        struct file *ashmem_area_vmfile(struct file *file) { return NULL; }
-        EXPORT_SYMBOL_GPL(is_ashmem_file);
-        EXPORT_SYMBOL_GPL(ashmem_area_name);
-        EXPORT_SYMBOL_GPL(ashmem_area_size);
-        EXPORT_SYMBOL_GPL(ashmem_area_vmfile);
-        EOF
-        fi
-
-        if [ -f common/drivers/android/binder/Makefile ]; then
-          perl -i -0777 -pe 's/\$\(\s*CONFIG_ANDROID_BINDER_IPC_RUST\s*\)/m/' common/drivers/android/binder/Makefile
-          #perl -i -ne 'print unless /CONFIG_ANDROID_BINDER_IPC_RUST_DUMMY/' common/drivers/android/binder/Makefile
-          perl -i -pe 's/^rust_binder-\$\([^)]+\)\s*:=/rust_binder-y :=/' common/drivers/android/binder/Makefile
-          cat common/drivers/android/Makefile
-          cat common/drivers/android/binder/Makefile
-          #perl -ni -e 'print unless /rust_toolchain\s*=\s*"\/\/build\/rust:linux_kernel_toolchain",/' common/BUILD.bazel
-          #cat common/BUILD.bazel
-          rustup set profile minimal
-          rustup update nightly
-          rustup default nightly
-          rustup target add aarch64-unknown-none
-        else
-          perl -i -0777 -pe 's/\$\(\s*CONFIG_ANDROID_BINDER_IPC_RUST\s*\)/m/' common/drivers/android/Makefile
-          cat common/drivers/android/Makefile
-        fi
-  
     - name: Change Kernel Name
       working-directory: ${{ env.KERNEL_ROOT }}
       run: |
@@ -520,10 +521,10 @@ jobs:
         if [ "${{ inputs.kernel_version }}" == "6.6" ] && [ "${{ inputs.kernel_version }}" == "6.12" ]; then
           if [ -z "${{ inputs.kernel_uname }}" ]; then
             echo "Didn't set kernel uname! Set to default value."
-            perl -i -0777 -pe 's/(.*)echo "\$\{KERNELVERSION\}\$\{file_localversion\}\$\{config_localversion\}\$\{LOCALVERSION\}\$\{scm_version\}"/$1echo "\${KERNELVERSION}\${file_localversion}\${config_localversion}\${LOCALVERSION}-${KSUVER}-Tam"/s' ./common/scripts/setlocalversion
+            perl -i -0777 -pe 's/(.*)echo "\$\{KERNELVERSION\}\$\{file_localversion\}\$\{config_localversion\}\$\{LOCALVERSION\}\$\{scm_version\}"/$1echo "\${KERNELVERSION}\${file_localversion}\${config_localversion}\${LOCALVERSION}-${KSUVER}-Tam\$\{scm_version\}"/s' ./common/scripts/setlocalversion
           else
             echo "Set kernel uname: ${{ inputs.kernel_uname }}!"
-            perl -i -0777 -pe 's/(.*)echo "\$\{KERNELVERSION\}\$\{file_localversion\}\$\{config_localversion\}\$\{LOCALVERSION\}\$\{scm_version\}"/$1echo "\${KERNELVERSION}\${file_localversion}\${config_localversion}\${LOCALVERSION}-${kernel_uname}"/s' ./common/scripts/setlocalversion
+            perl -i -0777 -pe 's/(.*)echo "\$\{KERNELVERSION\}\$\{file_localversion\}\$\{config_localversion\}\$\{LOCALVERSION\}\$\{scm_version\}"/$1echo "\${KERNELVERSION}\${file_localversion}\${config_localversion}\${LOCALVERSION}-${kernel_uname}\$\{scm_version\}"/s' ./common/scripts/setlocalversion
           fi
         else
           if [ -z "${{ inputs.kernel_uname }}" ]; then
@@ -549,7 +550,7 @@ jobs:
         fi
 
         # Commit changes to avoid dirty state during build
-        cd "$KERNEL_ROOT/kernel/common"
+        cd "$KERNEL_ROOT/common"
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
         git add .
@@ -560,14 +561,17 @@ jobs:
       run: |
         set -ex
         if [ "${{ inputs.kernel_variant }}" == "SUKI" ] && [ "${{ inputs.android_version }}" == "android13" ] && [ "${{ inputs.kernel_version }}" == "5.15" ]; then
-          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh || true
+          # Set ccache so rebuild kernel take less time
+          sudo apt update && sudo apt install ccache -y
+          ccache -M 10G
+          USE_CCACHE=1 LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh || true
           if [ ! -f "./out/android13-5.15/dist/Image" ]; then
             if [ ! -f "./out/android13-5.15/common/modules.order" ]; then
               exit 1
             else
               cp out/android13-5.15/common/modules.order common/android/gki_aarch64_modules
               echo "Building the kernel again..."
-              LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh || exit 1
+              USE_CCACHE=1 LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh || exit 1
             fi
           fi
         elif [ -f "build/build.sh" ]; then
@@ -615,67 +619,67 @@ jobs:
       working-directory: ${{ env.KERNEL_ROOT }}
       run: |
         if [ ${{ inputs.android_version }} == "android12" ] || [ ${{ inputs.android_version }} == "android13" ]; then
-          cp "$KERNEL_ROOT/out/${{ inputs.android_version }}-${{ inputs.kernel_version }}/dist/Image" "$BOOTIMGS"
-          cp "$KERNEL_ROOT/out/${{ inputs.android_version }}-${{ inputs.kernel_version }}/dist/Image.lz4" "$BOOTIMGS"
+          cp "$KERNEL_ROOT/out/${{ inputs.android_version }}-${{ inputs.kernel_version }}/dist/Image" "$BOOTIMGS/Image"
+          cp "$KERNEL_ROOT/out/${{ inputs.android_version }}-${{ inputs.kernel_version }}/dist/Image.lz4" "$BOOTIMGS/Image.lz4"
         else
-          cp "$KERNEL_ROOT/bazel-bin/common/kernel_aarch64/Image" "$BOOTIMGS"
-          cp "$KERNEL_ROOT/bazel-bin/common/kernel_aarch64/Image.lz4" "$BOOTIMGS"
+          cp "$KERNEL_ROOT/bazel-bin/common/kernel_aarch64/Image" "$BOOTIMGS/Image"
+          cp "$KERNEL_ROOT/bazel-bin/common/kernel_aarch64/Image.lz4" "$BOOTIMGS/Image.lz4"
         fi
         
         cd "$BOOTIMGS"
         # Create gzip of the Image file
         gzip -n -k -f -9 ./Image > ./Image.gz
         
-        GKI_URL=https://dl.google.com/android/gki/gki-certified-boot-android12-5.10-"${{ inputs.os_patch_level }}"_"${{ inputs.revision }}".zip
-        FALLBACK_URL=https://dl.google.com/android/gki/gki-certified-boot-android12-5.10-2023-01_r1.zip
-
-        # Check if the GKI URL is available
-        echo "Checking if GKI kernel URL is reachable: $GKI_URL"
-        status=$(curl -sL -w "%{http_code}" "$GKI_URL" -o /dev/null)
-
-        if [ "$status" = "200" ]; then
-          echo "[+] Downloading from GKI_URL"
-          curl -Lo gki-kernel.zip "$GKI_URL"
-        else
-          echo "[+] $GKI_URL not found, using $FALLBACK_URL"
-          curl -Lo gki-kernel.zip "$FALLBACK_URL"
-        fi
-
-        # Unzip the downloaded kernel and remove the zip
-        echo "Unzipping the downloaded kernel..."
-        unzip gki-kernel.zip && rm gki-kernel.zip
-
-        echo "Unpacking boot.img..."
-        FULL_PATH=$(pwd)/boot-5.10.img
-        echo "Unpacking using: $FULL_PATH"
-
-        echo "Running unpack_bootimg.py..."
-        $UNPACK_BOOTIMG --boot_img="$FULL_PATH"
-
         if [ ${{ inputs.android_version }} == "android12" ]; then
+          GKI_URL=https://dl.google.com/android/gki/gki-certified-boot-android12-5.10-"${{ inputs.os_patch_level }}"_"${{ inputs.revision }}".zip
+          FALLBACK_URL=https://dl.google.com/android/gki/gki-certified-boot-android12-5.10-2023-01_r1.zip
+
+          # Check if the GKI URL is available
+          echo "Checking if GKI kernel URL is reachable: $GKI_URL"
+          status=$(curl -sL -w "%{http_code}" "$GKI_URL" -o /dev/null)
+
+          if [ "$status" = "200" ]; then
+            echo "[+] Downloading from GKI_URL"
+            curl -Lo gki-kernel.zip "$GKI_URL"
+          else
+            echo "[+] $GKI_URL not found, using $FALLBACK_URL"
+            curl -Lo gki-kernel.zip "$FALLBACK_URL"
+          fi
+
+          # Unzip the downloaded kernel and remove the zip
+          echo "Unzipping the downloaded kernel..."
+          unzip gki-kernel.zip && rm gki-kernel.zip
+
+          echo "Unpacking boot.img..."
+          FULL_PATH=$(pwd)/boot-5.10.img
+          echo "Unpacking using: $FULL_PATH"
+
+          echo "Running unpack_bootimg.py..."
+          $UNPACK_BOOTIMG --boot_img="$FULL_PATH"
+
           $MKBOOTIMG --header_version 4 --kernel Image --output boot.img --ramdisk out/ramdisk --os_version 12.0.0 --os_patch_level "${{ inputs.os_patch_level }}"
           $AVBTOOL add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot.img --algorithm SHA256_RSA2048 --key $BOOT_SIGN_KEY
-          cp ./boot.img "$BOOTIMGS/${{ env.FILE_NAME }}-boot.img"
+          mv ./boot.img "$BOOTIMGS/${{ env.FILE_NAME }}-boot.img"
 
           $MKBOOTIMG --header_version 4 --kernel Image.gz --output boot-gz.img --ramdisk out/ramdisk --os_version 12.0.0 --os_patch_level "${{ inputs.os_patch_level }}"
           $AVBTOOL add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot-gz.img --algorithm SHA256_RSA2048 --key $BOOT_SIGN_KEY
-          cp ./boot-gz.img "$BOOTIMGS/${{ env.FILE_NAME }}-boot-gz.img"
+          mv ./boot-gz.img "$BOOTIMGS/${{ env.FILE_NAME }}-boot-gz.img"
 
           $MKBOOTIMG --header_version 4 --kernel Image.lz4 --output boot-lz4.img --ramdisk out/ramdisk --os_version 12.0.0 --os_patch_level "${{ inputs.os_patch_level }}"
           $AVBTOOL add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot-lz4.img --algorithm SHA256_RSA2048 --key $BOOT_SIGN_KEY
-          cp ./boot-lz4.img "$BOOTIMGS/${{ env.FILE_NAME }}-boot-lz4.img"
+          mv ./boot-lz4.img "$BOOTIMGS/${{ env.FILE_NAME }}-boot-lz4.img"
         else
           $MKBOOTIMG --header_version 4 --kernel Image --output boot.img
           $AVBTOOL add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot.img --algorithm SHA256_RSA2048 --key $BOOT_SIGN_KEY
-          cp ./boot.img "$BOOTIMGS/${{ env.FILE_NAME }}-boot.img"
+          mv ./boot.img "$BOOTIMGS/${{ env.FILE_NAME }}-boot.img"
           
           $MKBOOTIMG --header_version 4 --kernel Image.gz --output boot-gz.img
           $AVBTOOL add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot-gz.img --algorithm SHA256_RSA2048 --key $BOOT_SIGN_KEY
-          cp ./boot-gz.img "$BOOTIMGS/${{ env.FILE_NAME }}-boot-gz.img"
+          mv ./boot-gz.img "$BOOTIMGS/${{ env.FILE_NAME }}-boot-gz.img"
 
           $MKBOOTIMG --header_version 4 --kernel Image.lz4 --output boot-lz4.img
           $AVBTOOL add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot-lz4.img --algorithm SHA256_RSA2048 --key $BOOT_SIGN_KEY
-          cp ./boot-lz4.img "$BOOTIMGS/${{ env.FILE_NAME }}-boot-lz4.img"
+          mv ./boot-lz4.img "$BOOTIMGS/${{ env.FILE_NAME }}-boot-lz4.img"
         fi
         
     - name: Upload Artifacts (AnyKernel3)
